steps:
  # build the container image.
  - name: gcr.io/kaniko-project/executor
    args:
      - --destination=gcr.io/low-traffic/gsxjson
      - --cache=true
      - --cache-ttl=6h
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "gsxjson",
        "--image",
        "gcr.io/low-traffic/gsxjson",
        "--region",
        "asia-southeast1",
        "--platform",
        "managed",
        "--cpu",
        "1",
        "--memory",
        "1Gi",
        "--quiet",
      ]
timeout: 1200s
